#!/usr/bin/env bash
DJANGO_SETTINGS_MODULE=config.settings.dev \
DJANGO_SECRET_KEY='3p@)5@n!uw&tgx@vmthq*q%k&zu#-1y2%tx$eyx2j15)daht)7' \
POSTGRES_PASSWORD=123 \
DATABASE_NAME=pwdproj \
DATABASE_USER=pwdproj \
DATABASE_PASSWORD=pwdproj \
DATABASE_HOST=postgres \
docker-compose up
